/**
 * Every value here is read from the pretrained htdemucs checkpoint or from Demucs'
 * own source. Changing one without changing the model produces audio that is subtly
 * wrong rather than obviously broken, which is why `fft.test.ts` pins them against
 * fixtures generated by the reference Python.
 */

export const SAMPLE_RATE = 44100

/** `segment = Fraction(39, 5)` in the checkpoint, so 7.8s at 44.1 kHz. */
export const SEGMENT_SAMPLES = 343980

export const N_FFT = 4096

/** `_spec` asserts `hop == nfft // 4`. */
export const HOP = N_FFT / 4

/** `hop // 2 * 3`, the reflect padding `_spec` applies before the transform. */
export const SPEC_PAD = (HOP / 2) * 3

/** `torch.stft(center=True)` reflect-pads by half the window on each side. */
export const CENTER_PAD = N_FFT / 2

/** The Nyquist bin is dropped, so the model sees 2048 rather than 2049. */
export const BINS = N_FFT / 2

/** `ceil(SEGMENT_SAMPLES / HOP)`. */
export const FRAMES = Math.ceil(SEGMENT_SAMPLES / HOP)

/** `_spec` keeps `[..., 2 : 2 + frames]`, so two frames are dropped at each end. */
export const FRAME_TRIM = 2

/** Demucs' `--overlap` default. */
export const SEGMENT_OVERLAP = 0.25

/** Demucs' `transition_power` default. */
export const TRANSITION_POWER = 1

/**
 * Served through the Worker from R2, because Workers cap an individual static asset at
 * 25 MiB and the model is larger. The key is content-addressed, so the response can be
 * cached immutably and a new export is simply a new URL.
 */
export const MODEL_URL = '/lab/peelr/model.onnx'

/**
 * ONNX Runtime's own `.wasm` and `.mjs`, served from `public/`. At 23.13 MiB the
 * WebGPU runtime fits under the static asset cap, unlike the deprecated JSEP build.
 */
export const ORT_ASSET_PREFIX = '/peelr/ort/'

/**
 * Four stems plus the original, held as float samples, is roughly 127 MB per buffer at
 * this length. Longer inputs exhaust a laptop tab before they finish. See section 7 of
 * the plan.
 */
export const MAX_DURATION_SECONDS = 6 * 60

export const STEMS = ['drums', 'bass', 'other', 'vocals'] as const

export type Stem = (typeof STEMS)[number]
