/**
 * Every value here is read from the pretrained htdemucs checkpoint or from Demucs'
 * own source. Changing one without changing the model produces audio that is subtly
 * wrong rather than obviously broken, which is why `fft.test.ts` pins them against
 * fixtures generated by the reference Python/PyTorch.
 */

export const SAMPLE_RATE = 44100

/** `segment = Fraction(39, 5)` in the checkpoint, so 7.8s at 44.1 kHz. */
export const SEGMENT_SAMPLES = 343980

export const N_FFT = 4096

/** `_spec` asserts `hop == nfft // 4`. */
export const HOP = N_FFT / 4

/** `hop // 2 * 3`, the reflect padding `_spec` applies before the transform. */
export const SPEC_PAD = (HOP / 2) * 3

/** `torch.stft(center=True)` reflect-pads by half the window on each side. */
export const CENTER_PAD = N_FFT / 2

/** The Nyquist bin is dropped, so the model sees 2048 rather than 2049. */
export const BINS = N_FFT / 2

/** `ceil(SEGMENT_SAMPLES / HOP)`. */
export const FRAMES = Math.ceil(SEGMENT_SAMPLES / HOP)

/** `_spec` keeps `[..., 2 : 2 + frames]`, so two frames are dropped at each end. */
export const FRAME_TRIM = 2

/** Demucs' `--overlap` default. */
export const SEGMENT_OVERLAP = 0.25

/** Demucs' `transition_power` default. */
export const TRANSITION_POWER = 1

/**
 * First eight hex of the model file's sha256.
 *
 * It appears in both the URL the browser fetches and the R2 key behind it, so a new
 * export is a new URL. That is what makes the immutable cache header safe: without it,
 * a client that cached a bad model keeps it for a year and replacing the object in R2
 * changes nothing for them.
 */
export const MODEL_VERSION = '87bdf3b4'

/**
 * Served through the Worker from R2, because Workers cap an individual static asset at
 * 25 MiB and the model is larger.
 *
 * **The model stores fp16 weights but computes in fp32**, via `Cast` nodes on its
 * initializers. Converting the whole graph to fp16 instead halves nothing extra and
 * silently breaks the output: ONNX Runtime's WebGPU backend miscomputes the Conv1d time
 * branch in fp16, which measured 1.18 dB SNR against Python Demucs on drums where the
 * fp32 path measures 26.93 dB. Vocals survives it because that stem is almost entirely
 * the frequency branch, which is why the damage sounds like bleed rather than silence.
 */
export const MODEL_URL = `/lab/peelr/model-${MODEL_VERSION}.onnx`

/**
 * ONNX Runtime's own `.wasm` and `.mjs`, served from `public/`. They are static assets
 * rather than bundled ones so the 23 MiB binary never reaches the Worker script, which
 * Cloudflare caps at 3 MiB. `scripts/copy-ort-assets.mjs` puts them there.
 */
export const ORT_ASSET_PREFIX = '/peelr/ort/'

/**
 * Four stems plus the original, held as float samples, is roughly 127 MB per buffer at
 * this length. Longer inputs exhaust a laptop tab before they finish.
 */
export const MAX_DURATION_SECONDS = 6 * 60

export const STEMS = ['drums', 'bass', 'other', 'vocals'] as const

export type Stem = (typeof STEMS)[number]
