/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as LabHelloServerRouteImport } from './routes/lab/hello-server'
import { Route as LabPeelrRouteImport } from './routes/lab/peelr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabHelloServerRoute = LabHelloServerRouteImport.update({
  id: '/lab/hello-server',
  path: '/lab/hello-server',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPeelrRoute = LabPeelrRouteImport.update({
  id: '/lab/peelr',
  path: '/lab/peelr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab/hello-server': typeof LabHelloServerRoute
  '/lab/peelr': typeof LabPeelrRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/hello-server': typeof LabHelloServerRoute
  '/lab/peelr': typeof LabPeelrRoute
  '/lab': typeof LabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab/hello-server': typeof LabHelloServerRoute
  '/lab/peelr': typeof LabPeelrRoute
  '/lab/': typeof LabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lab/hello-server' | '/lab/peelr' | '/lab/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lab/hello-server' | '/lab/peelr' | '/lab'
  id: '__root__' | '/' | '/lab/hello-server' | '/lab/peelr' | '/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabHelloServerRoute: typeof LabHelloServerRoute
  LabPeelrRoute: typeof LabPeelrRoute
  LabIndexRoute: typeof LabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/hello-server': {
      id: '/lab/hello-server'
      path: '/lab/hello-server'
      fullPath: '/lab/hello-server'
      preLoaderRoute: typeof LabHelloServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/peelr': {
      id: '/lab/peelr'
      path: '/lab/peelr'
      fullPath: '/lab/peelr'
      preLoaderRoute: typeof LabPeelrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabHelloServerRoute: LabHelloServerRoute,
  LabPeelrRoute: LabPeelrRoute,
  LabIndexRoute: LabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
